### ISSUE TITLE
Update subgraph addresses for current contracts: 

### ISSUE THREAD

**Issue by Flip-Liquid** [0xbeedao/moloch-rises#35]
Board: https://mumbai.polygonscan.com/address/0x4bdd237de99fa5c92e197cfd0077ffb4069b4dba#code

Loot: https://mumbai.polygonscan.com/address/0x8fb0bf5cf1f7e1287253b7ad9671c6fa36ea21b1#code

Avatar: https://mumbai.polygonscan.com/address/0x2eaf87e63115070fbad8e5e9cd7bb25c2e1351a0#code

**Comment by 0xbeedao** [comment]
Done, new repo is live: https://github.com/CoinOp-Studios/moloch-rises-subgraph
with these updates. and the graph is here:  https://thegraph.com/hosted-service/subgraph/0xbeedao/moloch-rises-subgraph
